### PR TITLE
Adding variables STCG and LTCG which are taxed at special rates

### PR DESCRIPTION
**Pull request by sebastiansajie**
I have included STCG and LTCG variables which are reported in the form and also included the tax calculated on it.

### CODE REVIEW

**Comment by martinholmer** [comment]
@sebastiansajie,  Your pull request #63 looks good to me except for one small thing: once pull request #62 (which has been pending since Monday) is merged, your pull request will fail the new test added in #62.  See the format for the `records_variables.json` entries that the new test enforces in pull request #62.

On a broader issue: do you have any idea what schedule the TPRU staff are on with respect to reviewing/merging the pending #58, #60, #61, #62, and #63 pull requests?  I think it is appropriate for @andersonfrailey and @martinholmer to perhaps contribute pull requests, but I think the TPRU staff should be doing the reviewing (and possibly asking questions) and then either closing or merging the pull requests.

@indira-tpru @adc2-tpru @keshavchoudhary87

**Comment by keshavchoudhary87** [comment]
@martinholmer : Pull request no #58, 61 are waiting to be accepted due to need of some clarification and after reading the above comments please tell whether to accept the pull request no. #63 at all as it is remarked that it will fail the new test.

**Comment by martinholmer** [comment]
@keshavchoudhary87 asked:
> please tell whether to accept the pull request #63 at all as it is remarked that it will fail the new test.

If somebody will re-open pull request #62, I will be happy to revise the new test in #62 so that #63 does not fail the new test.  Can you re-open pull request #62?  If you want to do that, but aren't certain how to do that on GitHub, please ask a question here.

@indira-tpru @adc2-tpru @sebastiansajie

**Comment by sebastiansajie** [comment]
@martinholmer @andersonfrailey , could you please merge this pull request that includes variables for capital gains. Thanks.

**Comment by martinholmer** [comment]
@sebastiansajie said in pull request #63:
> could you please merge this pull request that includes variables for capital gains

I don't really want to do that for two reasons:
1. I don't have enough knowledge of the India personal income tax law to know if everything is correct.
2. I want to encourage TPRU team work by letting TPRU staff review and merge.

Does that make sense?

**Comment by martinholmer** [comment]
@keshavchoudhary87 said in pull request #63:
> A small doubt before I merge the pull request #63. In lines 87-90 of records_variables.json, the variable "Tax_short_term_apprate" seems to be picking up line 2 of Schedule SI. This is the same as "Tax_short_term_30per" and looks like double counting of the same variable. If a person lies in a lower tax bracket, the tax_short_term_apprate could be different from 30%.

Thanks for your review of PR #63.  My recommendation is to **not** merge this PR until it is discussed in New Delhi next week.  It is not needed immediately and the PR contains no policy parameters or logic (hence, is incomplete).

@indira-tpru @adc2-tpru @sebastiansajie @andersonfrailey

**Comment by martinholmer** [comment]
@sebastiansajie, Curious as to why you commented out the subsample test in pull request #63.

**Pull request merged**
