### PR TITLE
Updating app21_reform #58 as per martin's suggestions

### PR DESCRIPTION
**Pull request by sebastiansajie**
@martinholmer @adc2-tpru @keshavchoudhary87 
In order to move things forward, I have replicated all of @adc2-tpru changes made in #58 and further changes to it as suggested by Martin. Once this is through we could then incorporate all subsequent pull requests (i.e. those after #58).

### CODE REVIEW

**Comment by andersonfrailey** [comment]
Did your changes change change how `piax` is calculated? The tests are failing because the actual `pitax` isn't equal to the expected value.
screen shot 2018-10-29 at 1 41 05 pm

**Comment by sebastiansajie** [comment]
@andersonfrailey 

These are the lines that I added to functions.py

"""
    rebate = np.where(taxinc > rebate_thd, 0.,
                      np.minimum(rebate_rate * taxinc, rebate_ceiling))
    calc.array('rebate', rebate)
    tax = (rate1 * np.minimum(taxinc, tbrk1) +
           rate2 * np.minimum(tbrk2 - tbrk1,
                              np.maximum(0., taxinc - tbrk1)) +
           rate3 * np.minimum(tbrk3 - tbrk2,
                              np.maximum(0., taxinc - tbrk2)) +
           rate4 * np.maximum(0., taxinc - tbrk3))
    calc.array('tax_TTI', tax)
    tax = np.where(rebate > tax, 0, tax - rebate)
    surcharge = np.where(taxinc > surcharge_thd, tax * surcharge_rate, 0.)
    calc.array('surcharge', surcharge)
    tax = tax + surcharge
    cess = tax * cess_rate
    calc.array('cess', cess)
    tax = tax + cess
    calc.array('pitax', tax)
"""
This is exactly the same was what @martinholmer suggest to be changed. Could you please tell which are the two values being compared?

**Comment by sebastiansajie** [comment]
@andersonfrailey a correction, the last four lines are the ones that @martinholmer suggested to add (to calculate the cess and report it separately) . the other lines were there already.

**Comment by andersonfrailey** [comment]
@sebastiansajie, the test is comparing a hard coded value for total calculated `pitax` to the value computed when you run the calculator (see annotated screen shot)
screen shot 2018-10-29 at 2 05 29 pm

The test failure doesn't mean your code is wrong, just that by adding the `cess` calculations you changed the calculated value for `pitax`. If this is expected, then you can just update the hard coded value for `expect_pitax` in the test. If it's not, then you need to review your code.

As you add new parts of the tax code to the model you can expect this test to fail a lot. You just need to make sure that the change in value is expected and reasonable. For example, lets say you add an additional tax on income. Because you've added an additional tax, calculated `pitax` should go up. If, when you fail this test, you see that the calculated value for `pitax` goes up, you're probably ok. But if you see that `pitax` actually goes down then you probably have a problem with your code.

**Comment by sebastiansajie** [comment]
@andersonfrailey 
This is a new test that was introduced by @martinholmer because when #58 was sent it was not there so the changes passed the test.

For practical purposes, please suggest how to proceed. Are you saying that when ever we add new variables, which will invariably change pitax we need to do the calculations 'by hand' on the data given in the excel file and then stick it into the test file?

**Comment by andersonfrailey** [comment]
@sebastiansajie, you don't necessarily need to do the calculations by hand. You can just take the new value that is being calculated (see line 984 in the test report) and replace the old value in line 971.

**Comment by martinholmer** [comment]
@sebastiansajie said in issue #69:
> Could you please tell me why the test has failed. It fails at tax_calculator. Thanks.

Sorry, but I've been out of the office for most of the day.
@andersonfrailey's explanation in issue #69 is perfect.
@sebastiansajie,  does his explanation make sense to you?  Do you have any questions about how to proceed?

**Comment by sebastiansajie** [comment]
@martinholmer and @andersonfrailey 
I am now working on fixing the pull request pr-58 and want to change the hard coded value of pitax in the test_calculator to 1978.193e9. However I am facing a problem. Whenever I move to the branch pr-58 I don't "see" the files in my atom editor. When I move to master I do see the test file test_calculator. I am in a fix on how to proceed. 
capture test_calculator
capture test_calculator2

**Comment by martinholmer** [comment]
@sebastiansajie said in PR#69:
> I am now working on fixing the pull request pr-58 and want to change the hard coded value of pitax in the test_calculator to 1978.193e9. However I am facing a problem. Whenever I move to the branch pr-58 I don't "see" the files in my atom editor. When I move to master I do see the test file test_calculator.

I don't have any experience with the Atom editor, so I'm afraid I'm not going to be much help on this matter.

However, I am confused about why you posted this question to PR #69 (which proposes changes on the sebastiansajie:newreform branch) rather than to PR #70 (which proposes changes on the sebastiansajie:pr-58 branch).  Is there some confusion about which branch you're trying to edit?

**Comment by andersonfrailey** [comment]
@sebastiansajie, if you look at @adc2-tpru's fork of this repo, you can see that the `test_calculator.py` file is missing in both his master branch and the branch he used to make PR #58. So when you check out that branch the file is removed from your computer. Atom is showing all of the files correctly, `test_calculator.py` is just not in the branch you're on when you checkout #58.

It's possible that @adc2-tpru deleted the file at some point or just never merged in the upstream after this file was created (I can't remember if we included the tests from the beginning or added them later).

**Comment by martinholmer** [comment]
@sebastiansajie, @andersonfrailey's analysis is correct because the `test_calculator.py` file was added in PR #60, which was merge by @keshavchoudhary87 **after** the workshop (which was when PR #58 was originally created).   How to fix this?  Take the following four steps:

1. Close PR #69 (it's obsolete given your PR #70)

2. While on master branch, execute `gitsync` in order to get all recent master changes on your computer

3. Checkout the `pr-58` branch (`git checkout pr-58`) which is the basis of your PR #70

4. Execute `git merge master` (which will bring in recent master changes into your `pr-58` branch)

After doing these four steps, the `test_calculator.py` file should be visible on your `pr-58` branch.

Does this make sense?

**Comment by sebastiansajie** [comment]
I have closed this as it is a duplicate pull request. I have used a sub-branch of 58 to do the same.

**Pull request closed without merging**
