### PR TITLE
Incorporating Losses

### PR DESCRIPTION
**Pull request by kumar-ab**
@andersonfrailey @sebastiansajie @keshavchoudhary87 
I have included the Current Year Losses and the Brought Forward Losses in the model. These losses have to be set off from the sum of all heads of income to arrive at the Gross Total Income (GTI).

### CODE REVIEW

**Comment by sebastiansajie** [comment]
@martinholmer @andersonfrailey, I understood the first FAIL in the test calculator which essentially requires us to update _**pitax**_ to the new amount, However the second FAIL is quite abstruse. Could you tell us what is happening there?
image

The third FAIL, I guess would require us to update the distribution tables to the new amounts after the new field has been added. So we need to generate the tables and stick in the new amounts into the calculator. Am I right on this? However the error is on "assert 1==2"

**Comment by martinholmer** [comment]
@kumar-ab and @sebastiansajie,  Before answering the questions about pull request #81, be sure to review my pull request #83 about how to specify and use growfactors.  The first modifications that need to be made to pull request #81 is to change the growfactor names and apply them to READ (not CALC) variables.  Once those changes are made, we can proceed with a review of the logic changes in #81.  Does this make sense?

**Comment by kumar-ab** [comment]
@martinholmer 
Yes Martin, it totally makes sense. This part might have remained unnoticed because currently most of the CALC variables return the same value as the corresponding READ variables. However, going forward it has to be corrected. I will make the necessary changes to the code to ensure growfactors are applied to the READ variables.

**Comment by martinholmer** [comment]
@kumar-ab,  Why are you adding agricultural income to PR#83, which has to do with capital losses?
Much better to keep separate topics in separate pull requests.

**Comment by kumar-ab** [comment]
> @kumar-ab, Why are you adding agricultural income to PR#83, which has to do with capital losses?
> Much better to keep separate topics in separate pull requests.

As it had not been merged because of the test failure, I thought to continue working on the same branch. Was not sure if I can start a new branch before the first one in merged & synced.

**Comment by martinholmer** [comment]
@kumar-ab said in PR #81:
> Was not sure if I can start a new branch before the current one is either merged & synced or discarded.

To start of new branch that adds something unrelated to an old development branch, do this:
1.  Make sure all the code changes on the old branch have been committed.
2.  Do `git checkout master` to switch back to the master branch
3. Do `git checkout -b new-branch-name` to start a new development branch off the master branch.
(Obviously, you can replace `new-branch-name` with something relevant to your work.)

The basic point is that you can have several unrelated development branches active at the same time.

@sebastiansajie

**Comment by kumar-ab** [comment]
The changes incorporated in this branch is being done in a step by step manner through other branches. This pull request, thus, may be rejected. @sebastiansajie @martinholmer

**Pull request closed without merging**
