### PR TITLE
newreform

### PR DESCRIPTION
**Pull request by adc2-tpru**
this adds a new reform and changes caused by the reform in tax distribution - decile wise

### CODE REVIEW

**Comment by martinholmer** [comment]
@adc2-tpru,  Thanks for your innovative pull request #58.   By reading through your `app21.py` code, I learned about the Pandas `qcut` function, which I didn't know anything about.  So, I'm going to start using it in our USA Tax-Calculator.  Thanks for teaching me about this Pandas function.

I suggest you make one change before merging PR #58.  You added the calculated variable `cess` to the `records_variable.json` file, but didn't save its value.  Right now your PR #58 has the end of the `pitax_liability` function looking like this:
```
    calc.array('surcharge', surcharge)
    tax = tax + surcharge
    tax = (tax + surcharge)*(1 + cess_rate)
    calc.array('pitax', tax)
```
I suggest you revise that code to be something like this:
```
    calc.array('surcharge', surcharge)
    tax = tax + surcharge
    cess = tax * cess_rate
    calc.array('cess', cess)
    tax = tax + cess
    calc.array('pitax', tax)
```
Does that make sense?

@indira-tpru @keshavchoudhary87 @sebastiansajie

**Comment by keshavchoudhary87** [comment]
@martinholmer : 1. The above pull request modification as suggested by you makes a sense. But wanted to ask how to go about it? Whether a new pull request needs to be submitted after the corrections are made or I need to make suitable changes?
2. Also the app21_reforms.json file has a different reform than was originally in the Repo and the "app21_reform.py" file is also a separate name than the "reform.py" file in the Repo. So whether the merge will lead to subsuming of the codes of these new files in the old files without change in their names or these changes create new file like app21.py in addition to app2.py in  Repo ?

**Comment by martinholmer** [comment]
@keshavchoudhary87 said in PR #58:
> The above pull request modification as suggested by you makes sense. But wanted to ask how to go about it? Whether a new pull request needs to be submitted after the corrections are made or I need to make suitable changes?

The easiest way to make the [suggested changes](https://github.com/TPRU-demo/pitaxcalc-demo/pull/58#issuecomment-425758929) to PR #58 is for the following to happen:

1. @adc2-tpru opens the `newreform` branch on his computer.

**copy app21.py and app21_reform.json to new files if want to save them**

2. @adc2-tpru does:  `git rm app21.py`

3. @adc2-tpru does: `git rm app21_reform.json`

4. @adc2-tpru edits/saves:  `functions.py`

5. @adc2-tpru commits changes by doing:  `git commit -a -m "Save cess amount"

6. @adc2-tpru pushes committed changes to GitHub by doing: `git push origin newreform`

Thank's it; several small steps.  Much easier if @adc2-tpru does this rather than you.

@indira-tpru @sebastiansajie

**Comment by sebastiansajie** [comment]
@adc2-tpru could you please follow the instructions that @martinholmer gave above.

**Comment by martinholmer** [comment]
If @adc2-tpru does not have time to make the changes in PR #58 outlined in this [earlier comment](https://github.com/TPRU-demo/pitaxcalc-demo/pull/58#issuecomment-428606632), then there is a Plan B for @keshavchoudhary87.  Follow the steps in this [pull-request workflow document](https://github.com/open-source-economics/Tax-Calculator/blob/master/WORKFLOW.md#tax-calculator-pull-request-workflow) **except** instead of doing step 3 do `gitpr 58` (on Windows) or `./gitpr 58` (on Linux or a Mac).  The new development branch will be called `pr-58` and it will contain all the changes proposed in PR #58.  This branch can be edited as suggested in items 1-6 in that [earlier comment](https://github.com/TPRU-demo/pitaxcalc-demo/pull/58#issuecomment-428606632).  And then submitted as a new pull request (numbered 68 or higher if other pull requests or issues are opened before completing Plan B).  The new pull request can be merged and #58 closed (without merging).

**Comment by keshavchoudhary87** [comment]
@martinholmer : Since @adc2-tpru is out of station plan_B was attempted by me. But I am getting the error EQ was unexpected at this time:
```````````````````````````
![2018-10-15](https://user-images.githubusercontent.com/38851838/46945978-eecd4500-d093-11e8-9228-872028da62b9.png)
`````````````````````
so am I doing something other than what has been explained?

**Comment by martinholmer** [comment]
@keshavchoudhary87,  merged pull request #68 is an attempt to fix the bug you encountered using `gitpr.bat`.  I don't have a Windows computer to test the fix on, so I'm hoping (but not absolutely sure) that the fix is correct and complete.  

Please try again the procedure suggested in [this earlier comment](https://github.com/TPRU-demo/pitaxcalc-demo/pull/58#issuecomment-429666834).

**Comment by martinholmer** [comment]
Closing pull request #58 now that pull request #70 includes the cess enhancements originally included in #58.

**Pull request closed without merging**
