### PR TITLE
Updating #58

### PR DESCRIPTION
**Pull request by sebastiansajie**
Updating #58 which includes reform of adding a cess (additional tax) to the tax calculations.

### CODE REVIEW

**Comment by sebastiansajie** [comment]
@andersonfrailey I am getting a similar error.

**Comment by andersonfrailey** [comment]
@sebastiansajie see my [latest comment](https://github.com/TPRU-demo/pitaxcalc-demo/pull/69#issuecomment-434022905) on #69  for an explanation of the error and how to solve it.

**Comment by martinholmer** [comment]
@sebastiansajie, why are you opening a new PR #70 when you already had PR #69 open?
OK, I guess you did this to omit some unwanted code changes.
Fine.
If you're finished with the now obsolete PR #69, then close it without merging.

As far as I can see, PR #70 should **not** include the files `app21.py` or `app21_reform.json`.
Those files were just part of the workshop activities.  They are not appropriate for inclusion in the repository.
You can remove them using the `git rm app21.py` and `git rm app21_reform.json` commands and then commit and push to origin.

**Comment by martinholmer** [comment]
@sebastiansajie, Your pull request #70 looks great.
Why don't you ask @keshavchoudhary87 to review and merge it?

**Comment by sebastiansajie** [comment]
@keshavchoudhary87 could you please merge the pull request #70. Thanks.

**Pull request merged**
