### PR TITLE
Add distribution tables for India PIT law

### PR DESCRIPTION
**Pull request by martinholmer**
This pull request resolves issue #65 by adding distribution tables to the PITax calculator.  The subgroups are sorted by GTI.

Here is an example of the use of the new capability:
```
# dist-tables.py

import taxcalc as tc

# create current-law Calculator object calc1
rec = tc.Records()
pol = tc.Policy()
calc1 = tc.Calculator(policy=pol, records=rec)
assert calc1.current_year == 2017
calc1.calc_all()

# create policy-reform Calculator object calc2
reform = {2017: {'_rate2': [0.06]}}  # reform lowers rate from 10% to 6%
pol.implement_reform(reform)
calc2 = tc.Calculator(policy=pol, records=rec)
calc2.calc_all()
assert calc2.current_year == 2017

# create decile distribution tables for current law and policy reform
dt1, dt2 = calc1.distribution_tables(calc2, 'weighted_deciles')
print('Current-Law Distribution Table for 2017')
print(dt1)
print('Policy-Reform Distribution Table for 2017')
print(dt2)

"""
$ python dist-tables.py

Current-Law Distribution Table for 2017
           weight        ...                    pitax
0-10n           0        ...                        0
0-10z           0        ...                        0
0-10p   3,524,118        ...                        0
10-20   3,341,251        ...                        0
20-30   3,515,237        ...            1,540,277,852
30-40   3,515,237        ...            8,907,038,916
40-50   3,532,998        ...           17,064,193,114
50-60   3,524,118        ...           34,646,345,675
60-70   3,702,544        ...           75,783,006,310
70-80   3,524,118        ...          199,116,555,010
80-90   3,528,558        ...          432,866,876,267
90-100  3,532,998        ...        1,052,194,529,418
ALL    35,241,176        ...        1,822,118,822,561
90-95   1,766,499        ...          348,139,965,152
95-99   1,148,668        ...          395,334,232,019
Top 1%    617,831        ...          308,720,332,246


Policy-Reform Distribution Table for 2017
           weight        ...                    pitax
0-10n           0        ...                        0
0-10z           0        ...                        0
0-10p   3,524,118        ...                        0
10-20   3,341,251        ...                        0
20-30   3,515,237        ...                        0
30-40   3,515,237        ...            1,962,018,656
40-50   3,532,998        ...            5,711,348,379
50-60   3,524,118        ...           14,602,115,060
60-70   3,702,544        ...           45,502,588,366
70-80   3,524,118        ...          163,176,554,272
80-90   3,528,558        ...          397,795,460,459
90-100  3,532,998        ...        1,018,520,167,211
ALL    35,241,176        ...        1,647,270,252,404
90-95   1,766,499        ...          331,217,754,985
95-99   1,148,668        ...          384,398,972,927
Top 1%    617,831        ...          302,903,439,300
"""
```

### CODE REVIEW

**Comment by sebastiansajie** [comment]
@martinholmer @andersonfrailey This is quite a huge pull request. Thanks. 

I have two questions

1) Is it correct to say that in case we need to make changes to the GTI bins we need to modify this line in utils.py and make necessary changes to the test functions.

STANDARD_INCOME_BINS = [-9e99, -1e-9, 1e-9, 5e5, 10e5, 15e5, 20e5, 30e5, 40e5, 50e5, 100e5, 9e99]

2) I see that you have use a variable called 'GTI_baseline' in calculator.py and utlis.py. I am not sure how this variable is computed. Please explain.

**Comment by martinholmer** [comment]
@sebastiansajie asked in PR #80:
> Is it correct to say that in case we need to make changes to the GTI bins we need to modify this line in utils.py and make necessary changes to the test functions.
>```
>STANDARD_INCOME_BINS = [-9e99, -1e-9, 1e-9, 5e5, 10e5, 15e5, 20e5, 30e5, 40e5, 50e5, 100e5, 9e99]
>```

Yes, but there is one other thing you **MUST** do when making these kind of changes.
Make the `STANDARD_ROW_NAMES` list correspond to the revised `STANDARD_INCOME_BINS` list.  The names list is right above the `STANDARD_INCOME_BINS` list in the `utils.py` file.  That part of the `utils.py` file looks like this:
```
DECILE_ROW_NAMES = ['0-10n', '0-10z', '0-10p',
                    '10-20', '20-30', '30-40', '40-50',
                    '50-60', '60-70', '70-80', '80-90', '90-100',
                    'ALL',
                    '90-95', '95-99', 'Top 1%']

STANDARD_ROW_NAMES = ['<0', '=0', '0-5L', '5-10L', '10-15L',
                      '15-20L', '20-30L', '30-40L', '40-50L',
                      '50-100L', '>100L', 'ALL']

STANDARD_INCOME_BINS = [-9e99, -1e-9, 1e-9, 5e5, 10e5, 15e5, 20e5, 30e5,
                        40e5, 50e5, 100e5, 9e99]
```

**Comment by martinholmer** [comment]
@sebastiansajie asked in PR #80:
> I see that you have use a variable called `GTI_baseline` in `calculator.py` and `utlis.py`.   I am not sure how this variable is computed.   Please explain.

The `GTI_baseline` variable is computed in the `Calculator.distribution_tables` method here:
```
            assert calc.current_year == self.current_year
            assert calc.array_len == self.array_len
            var_dataframe = calc.distribution_table_dataframe()
            if have_same_income_measure(self, calc):
                imeasure = 'GTI'
            else:
                imeasure = 'GTI_baseline'
                var_dataframe[imeasure] = self.array('GTI')                <---------------
            dt2 = create_distribution_table(var_dataframe, groupby, imeasure)
```
The role of `GTI_baseline` is explained in that method's docstring:
```
    def distribution_tables(self, calc, groupby):
        """
        Get results from self and calc, sort them by GTI into table
        rows defined by groupby, compute grouped statistics, and
        return tables as a pair of Pandas dataframes.
        This method leaves the Calculator object(s) unchanged.
        Note that the returned tables have consistent income groups (based   <-------------
        on the self GTI) even though the baseline GTI in self and            <-------------
        the reform GTI in calc are different.                                <-------------

        Parameters
        ----------
        calc : Calculator object or None
            typically represents the reform while self represents the baseline;
            if calc is None, the second returned table is None

        groupby : String object
            options for input: 'weighted_deciles', 'standard_income_bins'
            determines how the columns in resulting Pandas DataFrame are sorted

        Return and typical usage
        ------------------------
        dist1, dist2 = calc1.distribution_tables(calc2, 'weighted_deciles')
        OR
        dist1, _ = calc1.distribution_tables(None, 'weighted_deciles')
        (where calc1 is a baseline Calculator object
        and calc2 is a reform Calculator object).
        Each of the dist1 and optional dist2 is a distribution table as a
        Pandas DataFrame with DIST_TABLE_COLUMNS and groupby rows.
        NOTE: when groupby is 'weighted_deciles', the returned tables have 3
              extra rows containing top-decile detail consisting of statistics
              for the 0.90-0.95 quantile range (bottom half of top decile),
              for the 0.95-0.99 quantile range, and
              for the 0.99-1.00 quantile range (top one percent); and the
              returned table splits the bottom decile into filing units with
              negative (denoted by a 0-10n row label),
              zero (denoted by a 0-10z row label), and
              positive (denoted by a 0-10p row label) values of the
              specified income_measure.
        """
```

**Comment by sebastiansajie** [comment]
@martinholmer , I ran the code for the distribution tables and it works well. However as there were too many columns, I outputted the tables to a csv file to be able to take a closer look. 
dt1.to_csv('Distribution Tables_Base.csv')
dt2.to_csv('Distribution Tables_Reform.csv')

I have a couple of questions, 
1. We also need the average burden per taxpayer. I would be able to divide each of the columns in the csv file with the weight and arrive at it. It would be good to have this as an option. No big deal though if this is not done as we need to work with the csv files in any case for reporting.
2. Would be possible to select specific columns(variables) into the tables. This would allow us to see specific columns while running the program.

Thanks.

**Pull request merged**
